- Handling warnings

In [68]:
import warnings
warnings.filterwarnings("ignore")

- Loading modules

In [69]:
import pandas as pd

- Auxiliar functions

In [70]:
def correct_format_rmssd(value):
    value = str(value)
    value = value.strip()
    value = value.replace(" ", "")
    value = value.replace(",", ".")
    return value

In [71]:
def categorize_age_group(age):
    """
    Categorizes age into defined elderly age groups based on Chilean health standards.

    Parameters:
    -----------
    age : int or float
        Age of the individual in years.

    Returns:
    --------
    str
        Age category as a string label.
    """
    if age < 60:
        return "Not elderly"
    elif 60 <= age <= 69:
        return "Young older adult"
    elif 70 <= age <= 79:
        return "Intermediate older adult"
    elif 80 <= age <= 89:
        return "Older adult"
    elif age >= 90:
        return "Very old adult"
    else:
        return "Unknown"

In [72]:
def categorize_bmi_elderly(bmi):
    """
    Categorizes BMI according to Chilean recommendations for elderly adults.

    Parameters:
    -----------
    bmi : float
        Body Mass Index (BMI) value in kg/m².

    Returns:
    --------
    str
        BMI category as a string label.
    """
    if pd.isnull(bmi):
        return "Null"
    elif bmi < 23:
        return "Underweight"
    elif 23 <= bmi <= 27.9:
        return "Normal weight"
    elif 28 <= bmi <= 31.9:
        return "Overweight"
    elif bmi >= 32:
        return "Obese"
    else:
        return "Unknown"

In [73]:
def categorize_map_elderly(map_value):
    """
    Categorizes Mean Arterial Pressure (MAP) in elderly individuals.

    Parameters:
    -----------
    map_value : float
        Mean Arterial Pressure (MAP) in mmHg.

    Returns:
    --------
    str
        MAP category label.
    """
    if pd.isnull(map_value):
        return "Unknown"
    elif map_value < 70:
        return "Low perfusion pressure"
    elif 70 <= map_value <= 99:
        return "Normal MAP"
    elif map_value >= 100:
        return "High MAP"
    else:
        return "Unknown"

- Reading and remove null columns from raw data

In [74]:
df_data = pd.read_excel("../raw_data/Basal v2.xlsx")
df_data

,Unnamed: 0,Unnamed: 1,redcap_repeat_instrument,sex,age,t2m_pre_mean_rr,t2m_pre_mean_hr,t2m_pre_sdnn,t2m_pre_rmssd,t2m_pre_hf,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,imc,weight kg,height cm,height mt
0,NaN,NaN,NaN,1,75,748.0,80.0,308.0,21.7,222,713,172,108,70,82.666667,38,27.343750,70.0,160,1.60
1,NaN,NaN,NaN,1,66,953.0,63.0,255.0,18.8,87,226,29,122,72,88.666667,50,23.422368,52.0,149,1.49
2,NaN,NaN,NaN,2,77,877.0,68.0,147.0,11.7,26,137,9,125,85,98.333333,40,28.027682,81.0,170,1.70
3,NaN,NaN,NaN,1,77,819.0,73.0,170.0,17.5,118,130,14,126,72,90.000000,54,33.203125,85.0,160,1.60
4,NaN,NaN,NaN,1,73,846.0,71.0,176.0,13.6,66,66,18,130,80,96.666667,50,30.261831,69.0,151,1.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,NaN,NaN,NaN,1,80,987.0,61.0,6.5,6.6,11,19,7,152,82,105.333333,70,29.007853,80.9,167,1.67
526,NaN,NaN,NaN,2,67,790.0,76.0,20.0,16.9,350,196,88,134,87,102.666667,47,28.714792,68.1,154,1.54
527,NaN,NaN,NaN,2,77,814.0,74.0,26.7,23.8,521,261,39,141,80,100.333333,61,29.042590,67.1,152,1.52
528,NaN,NaN,NaN,2,61,912.0,66.0,22.4,16.6,395,301,27,106,58,74.000000,48,22.252705,58.4,162,1.62
529,NaN,NaN,NaN,2,69,1016.0,NaN,18.9,16.9,604,189,16,111,72,85.000000,39,24.876543,80.6,180,1.80

In [75]:
df_data = df_data.drop(columns=["Unnamed: 0", "Unnamed: 1", "redcap_repeat_instrument"])
df_data.head()

,sex,age,t2m_pre_mean_rr,t2m_pre_mean_hr,t2m_pre_sdnn,t2m_pre_rmssd,t2m_pre_hf,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,imc,weight kg,height cm,height mt
0,1,75,748.0,80.0,308.0,21.7,222,713,172,108,70,82.666667,38,27.343750,70.0,160,1.60
1,1,66,953.0,63.0,255.0,18.8,87,226,29,122,72,88.666667,50,23.422368,52.0,149,1.49
2,2,77,877.0,68.0,147.0,11.7,26,137,9,125,85,98.333333,40,28.027682,81.0,170,1.70
3,1,77,819.0,73.0,170.0,17.5,118,130,14,126,72,90.000000,54,33.203125,85.0,160,1.60
4,1,73,846.0,71.0,176.0,13.6,66,66,18,130,80,96.666667,50,30.261831,69.0,151,1.51

In [76]:
df_data.shape

(530, 17)

In [77]:
df_data["sex"].value_counts()

1    366
2    164
Name: sex, dtype: int64

In [78]:
df_data.columns

Index(['sex', 'age', 't2m_pre_mean_rr', 't2m_pre_mean_hr', 't2m_pre_sdnn',
       't2m_pre_rmssd', 't2m_pre_hf', 't2m_pre_lf', 't2m_pre_vlf',
       'bp_systolic', 'bp_diastolic', 'bp_pam', 'bp_pp', 'imc', 'weight kg',
       'height cm', 'height mt'],
      dtype='object')

- Checking format data

In [79]:
df_data.dtypes

sex                  int64
age                  int64
t2m_pre_mean_rr    float64
t2m_pre_mean_hr    float64
t2m_pre_sdnn       float64
t2m_pre_rmssd       object
t2m_pre_hf           int64
t2m_pre_lf           int64
t2m_pre_vlf          int64
bp_systolic          int64
bp_diastolic         int64
bp_pam             float64
bp_pp                int64
imc                float64
weight kg          float64
height cm            int64
height mt          float64
dtype: object

- t2m_pre_rmssd has an incorrect format

In [80]:
df_data["t2m_pre_rmssd"] = df_data["t2m_pre_rmssd"].apply(correct_format_rmssd)
df_data["t2m_pre_rmssd"] = df_data["t2m_pre_rmssd"].astype(float)

- Modify sex

In [81]:
df_data["sex"] = df_data["sex"].replace({1:"Female", 2:"Male"})

- Checking Height, Weight, and IMC

In [82]:
df_data["check_height"] = (df_data["height mt"]*100).round(3) == df_data["height cm"].round(3)
df_data["check_height"].value_counts()

True     521
False      9
Name: check_height, dtype: int64

In [83]:
df_data[df_data["check_height"] == False]

,sex,age,t2m_pre_mean_rr,t2m_pre_mean_hr,t2m_pre_sdnn,t2m_pre_rmssd,t2m_pre_hf,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,imc,weight kg,height cm,height mt,check_height
444,Female,74,761.0,79.0,10.3,5.7,16,87,15,132,73,92.666667,59,29.384676,67.0,148,1.51,False
445,Male,71,615.0,98.0,10.6,5.8,4,39,17,133,90,104.333333,43,28.595237,65.2,175,1.51,False
446,Female,89,739.0,81.0,14.5,9.0,27,154,49,145,79,101.000000,66,30.612692,69.8,145,1.51,False
447,Female,70,924.0,65.0,9.9,10.8,17,44,56,117,58,77.666667,59,29.910969,68.2,148,1.51,False
448,Female,74,986.0,61.0,16.4,16.6,26,77,728,117,70,85.666667,47,29.910969,68.2,150,1.51,False
449,Female,71,955.0,63.0,14.3,17.8,6,55,853,152,85,107.333333,67,32.498575,74.1,155,1.51,False
450,Female,81,992.0,60.0,8.7,7.0,23,48,17,137,85,102.333333,52,28.463664,64.9,149,1.51,False
451,Female,83,772.0,78.0,8.7,11.6,8,7,54,142,80,100.666667,62,26.183062,59.7,149,1.51,False
452,Female,71,738.0,81.0,6.5,5.0,19,23,10,104,66,78.666667,38,34.252884,78.1,155,1.51,False

- Based on the analysis, the column height mt is incorrect and we will remove it

In [84]:
df_data = df_data.drop(columns=["height mt"])

In [85]:
df_data["updated_imc"] = df_data["weight kg"]/((df_data["height cm"]/100)*(df_data["height cm"]/100))
df_data["check_imc"] = df_data["imc"].round(3) == df_data["updated_imc"].round(3)
df_data["check_imc"].value_counts()

True     521
False      9
Name: check_imc, dtype: int64

In [86]:
df_data[df_data["check_imc"] == False]

,sex,age,t2m_pre_mean_rr,t2m_pre_mean_hr,t2m_pre_sdnn,t2m_pre_rmssd,t2m_pre_hf,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,imc,weight kg,height cm,check_height,updated_imc,check_imc
444,Female,74,761.0,79.0,10.3,5.7,16,87,15,132,73,92.666667,59,29.384676,67.0,148,False,30.588020,False
445,Male,71,615.0,98.0,10.6,5.8,4,39,17,133,90,104.333333,43,28.595237,65.2,175,False,21.289796,False
446,Female,89,739.0,81.0,14.5,9.0,27,154,49,145,79,101.000000,66,30.612692,69.8,145,False,33.198573,False
447,Female,70,924.0,65.0,9.9,10.8,17,44,56,117,58,77.666667,59,29.910969,68.2,148,False,31.135866,False
448,Female,74,986.0,61.0,16.4,16.6,26,77,728,117,70,85.666667,47,29.910969,68.2,150,False,30.311111,False
449,Female,71,955.0,63.0,14.3,17.8,6,55,853,152,85,107.333333,67,32.498575,74.1,155,False,30.842872,False
450,Female,81,992.0,60.0,8.7,7.0,23,48,17,137,85,102.333333,52,28.463664,64.9,149,False,29.232917,False
451,Female,83,772.0,78.0,8.7,11.6,8,7,54,142,80,100.666667,62,26.183062,59.7,149,False,26.890681,False
452,Female,71,738.0,81.0,6.5,5.0,19,23,10,104,66,78.666667,38,34.252884,78.1,155,False,32.507804,False

- The imc was calculated with the height in cm and was updated, the columns checks and imc will be removed

In [87]:
df_data.columns

Index(['sex', 'age', 't2m_pre_mean_rr', 't2m_pre_mean_hr', 't2m_pre_sdnn',
       't2m_pre_rmssd', 't2m_pre_hf', 't2m_pre_lf', 't2m_pre_vlf',
       'bp_systolic', 'bp_diastolic', 'bp_pam', 'bp_pp', 'imc', 'weight kg',
       'height cm', 'check_height', 'updated_imc', 'check_imc'],
      dtype='object')

In [88]:
df_data = df_data.drop(columns=['check_height', 'check_imc', 'imc'])

- Checking null values per column

In [89]:
data_null = []

for column in df_data.columns:
    is_null_columns=df_data[column].isna()
    counts = is_null_columns.value_counts()

    summary = {"Feature": column, "Null": 0, "Not_Null": 0}

    if False in counts.index:
        summary["Not_Null"] = counts[False]
    if True in counts.index:
        summary["Null"] = counts[True]
    
    data_null.append(summary)

df_summary_null = pd.DataFrame(data_null)
df_summary_null

            Feature  Null  Not_Null
0               sex     0       530
1               age     0       530
2   t2m_pre_mean_rr     0       530
3   t2m_pre_mean_hr     1       529
4      t2m_pre_sdnn    11       519
5     t2m_pre_rmssd     8       522
6        t2m_pre_hf     0       530
7        t2m_pre_lf     0       530
8       t2m_pre_vlf     0       530
9       bp_systolic     0       530
10     bp_diastolic     0       530
11           bp_pam     0       530
12            bp_pp     0       530
13        weight kg     0       530
14        height cm     0       530
15      updated_imc     0       530

- There are three attributes with null values, we will complete it with the average value. However, the average will be estimated based on the clusters associated with the generated categories.

- Making categories for:
    - Age
    - Pam
    - IMC

- We have not selected Bp as input to generate categories, because it is complicated to handle the variables at the same time with stricted rules. This implies that it is possible the generation of a high number of Unclassified examples.

In [90]:
df_data["age_category"] = df_data["age"].apply(categorize_age_group)
df_data["age_category"].value_counts()

Intermediate older adult    261
Young older adult           219
Older adult                  40
Not elderly                  10
Name: age_category, dtype: int64

In [91]:
df_data["bmi_category"] = df_data["updated_imc"].round(1).apply(categorize_bmi_elderly)
df_data["bmi_category"].value_counts()

Obese            184
Overweight       162
Normal weight    161
Underweight       23
Name: bmi_category, dtype: int64

In [92]:
df_data["pam_category"] = df_data["bp_pam"].round(0).apply(categorize_map_elderly)
df_data["pam_category"].value_counts()

Normal MAP                347
High MAP                  178
Low perfusion pressure      5
Name: pam_category, dtype: int64

- Now, we can complete the null values

In [93]:
df_summary_null

            Feature  Null  Not_Null
0               sex     0       530
1               age     0       530
2   t2m_pre_mean_rr     0       530
3   t2m_pre_mean_hr     1       529
4      t2m_pre_sdnn    11       519
5     t2m_pre_rmssd     8       522
6        t2m_pre_hf     0       530
7        t2m_pre_lf     0       530
8       t2m_pre_vlf     0       530
9       bp_systolic     0       530
10     bp_diastolic     0       530
11           bp_pam     0       530
12            bp_pp     0       530
13        weight kg     0       530
14        height cm     0       530
15      updated_imc     0       530

In [94]:
for features in ["t2m_pre_sdnn", "t2m_pre_rmssd", "t2m_pre_mean_hr"]:
    df_data[f"is_null_{features}"] = df_data[features].isna()

    filter_value = df_data[df_data[f"is_null_{features}"]]

    for index in filter_value.index:
        age_category = filter_value["age_category"][index]
        bmi_category = filter_value["bmi_category"][index]
        pam_category = filter_value["pam_category"][index]
        sex = filter_value["sex"][index]

        df_with_categories = df_data[(df_data['age_category'] == age_category) &
                                    (df_data['bmi_category'] == bmi_category) &
                                    (df_data['pam_category'] == pam_category) &
                                    (df_data['sex'] == sex)]
        
        average = df_with_categories[features].mean()

        df_data[features][index] = average

- Export processed dataset for next analysis

In [96]:
df_data.to_csv("../results/processed_dataset.csv", index=False)